name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_django_job:
    uses: RahulRimal/cfe-dj-k8/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: super-secret-key

    steps:
      - uses: actions/checkout@v4